name: Update Weibo New Content

on:
  schedule:
    # UTC time 22:00 and 0:00 (China time 6:00 and 8:00)
    - cron: "0 22 * * *"
    - cron: "0 0 * * *"
    # UTC time 2:00 to 12:00, every 2 hours (China time 10:00 to 20:00)
    - cron: "0 2,4,6,8,10,12 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-content:
    runs-on: ubuntu-24.04
    permissions:
      contents: write # Explicitly specify write permission

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # Enable pip cache

      - name: Install dependencies
        working-directory: ./rss
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate content
        run: |
          python rss/generate_content.py
        env:
          TZ: Asia/Shanghai # Set timezone to China time

      - name: Update latest.html
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add rss/latest.html
          git commit -m "Auto update content" -q --no-verify
          git push -q "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" HEAD:${{ github.ref }}
