name: Update Weibo Content

on:
  schedule:
    - cron: '0 * * * *' # 每小时的0分触发
    workflow_dispatch:  # 允许手动触发
jobs:
  update-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests lxml jinja2 python-dateutil pytz

      - name: Generate content
        run: |
          python rss/generate_content.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add rss/latest.html
          git commit -m "Auto update content at $(date)"
          git push "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"